{
  "name": "test_myanswaer[3-8]",
  "status": "failed",
  "statusDetails": {
    "message": "AssertionError: assert 4 == 8\n  +4\n  -8",
    "trace": "a = 3, b = 8\n\n    @pytest.mark.parametrize('a,b', [(1, 2), (3, 8), ('a1', 'b1')])\n    def test_myanswaer(a, b):\n>       assert func(a) == b\nE       assert 4 == 8\nE         +4\nE         -8\n\ntest_a.py:30: AssertionError"
  },
  "parameters": [
    {
      "name": "a",
      "value": "3"
    },
    {
      "name": "b",
      "value": "8"
    }
  ],
  "start": 1609053552845,
  "stop": 1609053552845,
  "uuid": "4e6ce362-2476-42ad-bd52-b66df122b133",
  "historyId": "91f6ea91aaf1384a62b38f5494e234eb",
  "testCaseId": "2589ccc839f51021e27ae6b1e1078d60",
  "fullName": "test_a#test_myanswaer",
  "labels": [
    {
      "name": "suite",
      "value": "test_a"
    },
    {
      "name": "host",
      "value": "WJ-PC"
    },
    {
      "name": "thread",
      "value": "8460-MainThread"
    },
    {
      "name": "framework",
      "value": "pytest"
    },
    {
      "name": "language",
      "value": "cpython3"
    },
    {
      "name": "package",
      "value": "test_a"
    }
  ]
}